@startuml
!include ../../../base.puml

interface ISpeechToTextStep <<interface>>{
  +transcribe(...):...
  +transcribe(...):...
}

class SpeechToTextStep implements ISpeechToTextStep{
  +transcribe(...):...
  +transcribe(...):...
}

class NewSpeechToTextStep implements ISpeechToTextStep{
  transcribe(...)...
  transcribe(...)...
}
@enduml
